wandb_version: 1

input_shape:
  desc: null
  value:
  - 84
  - 84
  - 4
batch_size:
  desc: null
  value: 256
n_updates:
  desc: null
  value: 5000
hidden:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.0001
gamma:
  desc: null
  value: 0.99
value_c:
  desc: null
  value: 0.5
entropy_c:
  desc: null
  value: 0.01
clip_ratio:
  desc: null
  value: 0.1
std_adv:
  desc: null
  value: true
agent:
  desc: null
  value: PPO
operating_system:
  desc: null
  value: nt
_wandb:
  desc: null
  value:
    python_version: 3.9.22
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748873748.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.9.22
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
