wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 256
agent:
  desc: null
  value: PPO
operating_system:
  desc: null
  value: nt
_wandb:
  desc: null
  value:
    python_version: 3.9.22
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748867399.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.9.22
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
